//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf3rab.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autorizacia> Autorizacia { get; set; }
        public virtual DbSet<Doljnost> Doljnost { get; set; }
        public virtual DbSet<Grafik_rabot> Grafik_rabot { get; set; }
        public virtual DbSet<Mesta_dobichi> Mesta_dobichi { get; set; }
        public virtual DbSet<Metalli> Metalli { get; set; }
        public virtual DbSet<Oborudovanie> Oborudovanie { get; set; }
        public virtual DbSet<Otchet_smeni> Otchet_smeni { get; set; }
        public virtual DbSet<Pasport> Pasport { get; set; }
        public virtual DbSet<Pol> Pol { get; set; }
        public virtual DbSet<Postavshiki> Postavshiki { get; set; }
        public virtual DbSet<Propiska> Propiska { get; set; }
        public virtual DbSet<Smena> Smena { get; set; }
        public virtual DbSet<Smotryashiy> Smotryashiy { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vid_mestorozhdeniya> vid_mestorozhdeniya { get; set; }
        public virtual DbSet<Zayavki_na_oborudovanie> Zayavki_na_oborudovanie { get; set; }
    }
}
