//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf3rab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudnik()
        {
            this.Autorizacia = new HashSet<Autorizacia>();
            this.Grafik_rabot = new HashSet<Grafik_rabot>();
            this.Smotryashiy = new HashSet<Smotryashiy>();
            this.Zayavki_na_oborudovanie = new HashSet<Zayavki_na_oborudovanie>();
        }
    
        public int ID_Sotrudnik { get; set; }
        public Nullable<int> ID_Pasport { get; set; }
        public Nullable<decimal> Oklad { get; set; }
        public string Nomer_telephona { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Data_nachala_rabot { get; set; }
        public string Data_uvolneniya { get; set; }
        public Nullable<int> ID_Doljnost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorizacia> Autorizacia { get; set; }
        public virtual Doljnost Doljnost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grafik_rabot> Grafik_rabot { get; set; }
        public virtual Pasport Pasport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Smotryashiy> Smotryashiy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zayavki_na_oborudovanie> Zayavki_na_oborudovanie { get; set; }
    }
}
