//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf3rab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavki_na_oborudovanie
    {
        public int ID_Zayavki_na_zakaz_oborudovaniya { get; set; }
        public Nullable<int> ID_Postavshika_oborudovaniya { get; set; }
        public Nullable<int> ID_oborudovaniya { get; set; }
        public Nullable<int> Kolichestvo_postavlyaemogo_oborudovaniya { get; set; }
        public Nullable<int> ID_Sotrudnik { get; set; }
    
        public virtual Oborudovanie Oborudovanie { get; set; }
        public virtual Postavshiki Postavshiki { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
